### ISSUE TITLE
handle app killed scenario of stop tracking state and follow the same state of the app after the app restart 

### ISSUE THREAD

**Issue by LOG-TAG** [hypertrack/quickstart-flutter#4]
in this sample app sticky notification clicking state scenario  not working properly on when app killed from recent apps 

Steps to reproduce:
1)run the sample
2)start the tracking 
3)press back or home button and kill the app
4>then click on the sticky notification it should open the app with 'Stop Tracking' instead of 'start tracking' since already a previous start tracking process is running there

it is the important thing since apps might kill at any time and restart for the delivery boy android mobile scenario, please provide this fix in the flutter sample itself

**Comment by deniszpua** [comment]
@LOG-TAG FYI ^^^

**Comment by LOG-TAG** [comment]
thanks for the quick fix, any plans for **hypertrack/views-android** clone for flutter ?

**Comment by deniszpua** [comment]
@LOG-TAG Nobody requested it before. You can create a feature request [here](https://hypertrack.canny.io/feature-requests)
