### ISSUE TITLE
background_fetch SDK needed to  reload the app 

### ISSUE THREAD

**Issue by LOG-TAG** [hypertrack/quickstart-flutter#5]
https://pub.dev/packages/https://pub.dev/packages/background_fetch

above integration needed to enable background to reload the app when app in the killed state, platform level handling needed to continuing the events created for proceeding tracking

**Comment by deniszpua** [comment]
@LOG-TAG could you, plz, provide more context for this? On Android we don't use _background_ tracking, so I've never seen SDK been killed without customer action (via settings or power-saving software). As for the iOS, after been killed app becomes active if there were more or less significant displacement of the phone. 
Based on the written above, I don't see any value in adding this dependency.

@aashsub90 @tulushev FYI
